# None as otherwise it clobbers our compiler choce
language: none

# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

# The default build
env: CXX=g++-6 CC=gcc-6
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y uuid-dev libexpat1-dev libsqlite3-dev libmysqlclient-dev libmagic-dev libexif-dev libcurl4-openssl-dev cmake3
  - sudo ./scripts/install-duktape.sh
  - sudo ./scripts/install-pupnp18.sh
  - sudo ./scripts/install-taglib111.sh
  - sudo ./scripts/install-googletest.sh

# Build
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DWITH_SYSTEMD=0 -DWITH_TESTS=1 .. && make && make test ARGS=-V

matrix:
  include:
    - stage: Build Gerbera
    - env: CXX=g++-4.9 CC=gcc-4.9
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
    - env: CXX=g++-5 CC=gcc-5
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
    - env: CXX=clang++-4.0 CC=clang-4.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-4.0
          packages:
            - libc++-dev
            - clang-4.0
    - stage: Test Gerbera UI
      addons:
        chrome: stable
      before_install: skip
      install:
        - npm --prefix $TRAVIS_BUILD_DIR/gerbera-web/ install $TRAVIS_BUILD_DIR/gerbera-web/
      script:
        - npm --prefix $TRAVIS_BUILD_DIR/gerbera-web run lint
        - npm --prefix $TRAVIS_BUILD_DIR/gerbera-web run test
        - npm --prefix $TRAVIS_BUILD_DIR/gerbera-web run test:e2e
