# None as otherwise it clobbers our compiler choce
language: none

# Ubuntu 16.04 Xenial support
sudo: required
dist: xenial

# The default build
env: CXX=g++-7 CC=gcc-7
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y uuid-dev libexpat1-dev libsqlite3-dev libmysqlclient-dev libmagic-dev libexif-dev libcurl4-openssl-dev cmake3
  - sudo ./scripts/install-duktape.sh
  - sudo ./scripts/install-pupnp18.sh
  - sudo ./scripts/install-taglib111.sh
  - sudo ./scripts/install-googletest.sh

# Build
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_VERBOSE_MAKEFILE=ON -DWITH_SYSTEMD=0 -DWITH_TESTS=1 .. && make && make test ARGS=-V

matrix:
  include:
    - stage: Build Gerbera
    - env: CXX=g++-8 CC=gcc-8
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-8
    - env: CXX=clang++-6.0 CC=clang-6.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-xenial-6.0
          packages:
            - libc++-dev
            - clang-6.0
    - stage: Test Gerbera UI
      addons:
        chrome: stable
      before_install: skip
      install:
        - npm --prefix $TRAVIS_BUILD_DIR/gerbera-web/ install $TRAVIS_BUILD_DIR/gerbera-web/
      script:
        - npm --prefix $TRAVIS_BUILD_DIR/gerbera-web run lint
        - npm --prefix $TRAVIS_BUILD_DIR/gerbera-web run test
        - npm --prefix $TRAVIS_BUILD_DIR/gerbera-web run test:e2e
